### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tbergen1** [DMLoosley/sql-scratch-capstone-turn-in#1]
### Criteria 1: Report
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Your slides are well done.  They are clean and display all of the relevant data in a nice format.  I also thought your inclusion of the queries, along with descriptions of what those queries were doing was a nice touch.  It really showed that you understood what was going on.  I also liked the inclusion of graphs to display the data in a more digestible manner.  Awesome job!

### Criteria 2: Query Accuracy
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: All queries accurately retrieve the data intended.  Great job!

### Criteria 3: Query Formatting
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Queries adhere to the rules of the style guide.  Formatting is extremely important, especially in larger queries, so it's great that you paid attention when writing yours.

### Criteria 4: Understanding underlying concepts and terminology
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Your report demonstrated an understanding of the concepts of attribution.  You provided great definitions for core concepts sure as the difference between campaigns and soures.  You also gave good advice to the company regarding what course it should take when reinvesting.  Additionally, you gave a great breakdown of the user journey, which was really detailed.  Great job!

### Overall Score: 16/16
Overall, you did a great job with this.  You demonstrated clear understanding of the material and developed a good looking, clean report on your findings.  All of your conclusions were supported with evidence coming from well-formatted, accurate queries.  Keep up the good work!

**Comment by DMLoosley** [comment]
Thank you for your comments!  This course was interesting and challenging - I will definitely take more classes.
